title: My Blog
email: dm.klionsky@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  ten0s

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-166991530-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
