title: My Blog
email: dm.klionsky@gmail.com
baseurl: ""                    # the subpath of your site, e.g. /blog
url: "https://ten0s.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  ten0s

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path:    "404.html"
    values:
      sitemap: false
  - scope:
      path:    "yandex_9d4bd434e638f51b.html"
    values:
      sitemap: false
  - scope:
      path:    "BingSiteAuth.xmll"
    values:
      sitemap: false

google_analytics: UA-166991530-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
